---
title: "shinyapp"
author: "Danielle Sclafani"
date: "2/9/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


library(here)
library(janitor)
library(sf)
library(tmap)
library(sp)
library(rnaturalearthdata)
library(rgeos)
library(tidyverse)
library(viridis)
```


```{r}
# reading in the data
parks_data <- read_csv(here("data", "parks.csv")) 

parks_data_ca <- parks_data%>% 
  clean_names() %>% 
  filter(state %in% c("CA", "CA, NV"))


species_data <- read_csv(here("data", "species.csv")) 

species_data_ca <- species_data %>% 
  clean_names() %>% 
  filter(park_name %in% c("Channel Islands National Park", "Death Valley National Park", "Joshua Tree National Park", "Lassen Volcanic National Park", "Pinnacles National Park", "Redwood National Park", "Sequoia and Kings National Park", "Yosemite National Park")) %>% 
  mutate(common_names = tolower(common_names))

species_category_all <- species_data %>% 
      group_by("Park Name", Category) %>% 
      count()
```


```{r}
# widget 1 - radio button, pulls up maps of each park - the picture of the park (CA only) code is already done for this widget, it is just not working

```

```{r}
# widget 2 - Bar graph of species category - drop down menu widget

species_category <- species_data_ca %>% 
  clean_names() %>% 
  group_by(park_name, category) %>% 
  count()


ggplot(data = species_category, aes(x = park_name, y = n)) +
  geom_col(aes(fill = category)) +
  coord_flip() +
  theme_bw() +
  theme(legend.position = "none") +
  labs(x = "", y = "Number of Species") +
  facet_wrap(~category) +
  scale_color_viridis(discrete = TRUE)+
  scale_fill_viridis(discrete = TRUE) +
  geom_text(aes(label=n, vjust = -0.3))
  

```


```{r}
# map code for widgets  3 and 4
park_boundaries <- 
  st_read(
    here("data", 
         "ne_10m_parks_and_protected_lands" ,
         "ne_10m_parks_and_protected_lands_area.shp")
  ) %>% 
  clean_names() %>% 
  select("name", "nps_region")

tmap_mode("view")

map_1<- tm_basemap("Esri.WorldTopoMap")+
tm_shape(park_boundaries) +
  tm_polygons(alpha = 0.5)

map_1
```



```{r}
# widget 3 textbox widget - type in the animal to see which park it lives in.

#reactive data frame 
#species_name_reactive <- reactive({
#    species_data %>% 
#      filter(str_detect(common_names, pattern = input$species_locator))
#  })

#example code - need str_detect - using the combined data frame species_park_bound

fox_select <- species_park_bound %>% 
  filter(str_detect(common_names, pattern ="fox")) %>% #fox will be the inputId
  select(common_names, name, geometry)

#trying to get only the parks that show up in the fox data frame to come up in the map

tm_shape(fox_select)
```

```{r}
#widget 4 - interactive map of all national parks in the US (all 61) - checkbox

# this will be the interactive data frame 
#region_select <- reactive({park_boundaries %>% 
#  filter(nps_region %in% c(input$selected_region))
#)}
```


```{r}
#widget 5 - possible biodiversity index widget


```


## Trying to combine 3 datasets into one

```{r}
#selecting only necessary values for species data
species_data_v2 <- read_csv(here("data", "species.csv")) %>% 
  clean_names()

species_name_data <- species_data_v2 %>% 
  filter(occurrence == "Present")  %>% 
   mutate(name = case_when(park_name == "Sequoia and Kings Canyon National Parks" ~ "Sequoia",
                           park_name == "Channel Islands National Park" ~ "Channel Islands",
                           park_name == "Redwood National Park" ~ "Redwood",
                           park_name == "Death Valley National Park" ~ "Death Valley",
                           park_name == "Joshua Tree National Park" ~ "Joshua Tree",
                           park_name == "Lassen Volcanic National Park" ~ "Lassen Volcanic",
                           park_name == "Yosemite National Park" ~ "Yosemite",
                           park_name == "Pinnacles National Park" ~ "Pinnacles",
                           park_name == "Badlands National Park" ~ "Badlands",
                           park_name == "Big Bend National Park" ~ "Big Bend",
                           park_name == "Canyonlands National Park" ~ "Canyonlands",
                           park_name == "Capitol Reef National Park" ~ "Capital Reef",
                           park_name == "Crater Lake National Park" ~ "Crater Lake",
                           park_name == "Denali National Park and Preserve" ~ "Denali",
                           park_name == "Everglades National Park" ~ "Everglades",
                           park_name == "Gates of the Arctic National Park and Preserve" ~ "Gates of the Artic",
                           park_name == "Glacier National Park" ~ "Glacier",
                           park_name == "Glacier Bay National Park and Preserve" ~ "Glacier Bay",
                           park_name == "Grand Canyon National Park" ~"Grand Canyon",
                           park_name == "Great Sand Dunes National Park and Preserve" ~ "Great Sand Dunes",
                           park_name ==  "Great Smoky Mountations National Park" ~ "Great Smoky Mountains",
                           park_name ==  "Grand Teton National Park" ~ "Grand Teton",
                           park_name == "Hawaii Volcanoes National Park" ~ "Hawai'i Volcanoes",
                           park_name == "Isle Royale National Park" ~ "Isle Royale",
                           park_name == "Katmai National Park and Preserve" ~ "Katmai",
                           park_name == "Kenai Fjords National Park" ~ "Kenai Fjords",
                           park_name == "Kobuk Valley National Park" ~ "Kobuk Valley",
                           park_name == "Lake Clark National Park and Preserve" ~ "Lake Clark",
                           park_name == "Mount Rainer National Park" ~ "Mount Rainer",
                           park_name == "North Cascades National Park" ~ "North Cascades",
                           park_name == "Olympic National Park" ~ "Olympic",
                           park_name == "Petrified Forest National Park" ~ "Petrified Forest",
                           park_name == "Rocky Mountain National Park" ~ "Rocky Mountain",
                           park_name == "Shenandoah National Park" ~ "Shenandoah",
                           park_name == "Voyageurs National Park" ~ "Voyageurs",
                           park_name == "Wrangell - St Elias National Park and Preserve" ~ "Wrangell-St Elias",
                           park_name == "Yellowstone National Park" ~ "Yellowstone",
                           park_name == "Zion National Park" ~ "Zion"))%>% 
  mutate(common_names = tolower(common_names))# so when user types in animal name in lower case it will detect it


#renaming park_code to unit_code in order to match the park boundaries dataset
park_data_v2 <- read_csv(here("data", "parks.csv"))%>% 
  clean_names() %>% 
  rename(unit_code = park_code) %>% 
   mutate(name = case_when(
    park_name == "Sequoia and Kings Canyon National Parks" ~ "Sequoia",
    park_name == "Channel Islands National Park" ~ "Channel Islands",
    park_name == "Redwood National Park" ~ "Redwood",
    park_name == "Death Valley National Park" ~ "Death Valley",
    park_name == "Joshua Tree National Park" ~ "Joshua Tree",
    park_name == "Lassen Volcanic National Park" ~ "Lassen Volcanic",
    park_name == "Yosemite National Park" ~ "Yosement",
    park_name == "Pinnacles National Park" ~ "Pinnacles"))


#combining park data  with park boundary data (contains all 7 NPs in CA)
park_data_bound <- merge(park_boundaries, park_data_v2, by = "name")


#combining the above combined dataset with the species data set by the name of the park (contains all 7 NPs in CA)
species_park_bound <- merge(park_data_bound, species_data_v2, by = "name")

st_crs(species_park_bound)

tm_shape(species_park_bound)+
  tm_polygons(aes(color = "blue"))
```



### trying to run species locator a an SF
```{r}
us_states <- st_read(here("data", "us_states","States_shapefile.shp"))

main_land <-us_states %>% 
  filter(State_Code != "AK") %>% 
  filter(State_Name != "HAWAII")
  
main_park_bound <- park_boundaries %>% 
  filter(nps_region != "Alaska") %>% 
  filter(unit_code != "HAVO")
  
ggplot()+
  geom_sf(data = main_land)+
  geom_sf(data = main_park_bound)+ # need this data frame to have species in it.
  theme_minimal()
```

US_Shapefile link: https://hub.arcgis.com/datasets/1b02c87f62d24508970dc1a6df80c98e_0/data